# Generated by Django 5.2.17 on 2026-09-02 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='과목 코드')),
                ('name', models.CharField(max_length=150, verbose_name='과목명')),
                ('default_credits', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10)], verbose_name='기본 학점')),
                ('status', models.CharField(choices=[('active', '활성'), ('inactive', '비활성')], default='active', max_length=20, verbose_name='과목 상태')),
                ('description', models.TextField(blank=True, verbose_name='과목 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '과목',
                'verbose_name_plural': '과목',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='전공 코드')),
                ('name', models.CharField(max_length=100, verbose_name='전공명')),
                ('college_name', models.CharField(blank=True, max_length=100, verbose_name='단과대학')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '전공',
                'verbose_name_plural': '전공',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='학년도')),
                ('semester', models.CharField(choices=[('first', '1학기'), ('summer', '여름학기'), ('second', '2학기'), ('winter', '겨울학기')], max_length=10, verbose_name='학기')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('is_current', models.BooleanField(default=False, verbose_name='현재 학기')),
            ],
            options={
                'verbose_name': '학기',
                'verbose_name_plural': '학기',
                'ordering': ['-year', 'semester'],
                'constraints': [models.UniqueConstraint(fields=('year', 'semester'), name='unique_academic_term'), models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='unique_current_academic_term'), models.CheckConstraint(condition=models.Q(('year__gte', 2000), ('year__lte', 2100)), name='academic_term_year_range'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='academic_term_valid_date_range')],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=10, verbose_name='분반')),
                ('credits', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(10)], verbose_name='개설 학점')),
                ('professor_name', models.CharField(blank=True, max_length=100, verbose_name='담당 교수')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='수강 정원')),
                ('status', models.CharField(choices=[('scheduled', '개설 예정'), ('open', '수강 가능'), ('closed', '마감'), ('cancelled', '폐강')], default='scheduled', max_length=20, verbose_name='개설 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academic.course', verbose_name='과목')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='academic.academicterm', verbose_name='개설 학기')),
            ],
            options={
                'verbose_name': '개설 강좌',
                'verbose_name_plural': '개설 강좌',
                'ordering': ['-term__year', 'course__code', 'section_number'],
            },
        ),
        migrations.CreateModel(
            name='CourseMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('mon', '월요일'), ('tue', '화요일'), ('wed', '수요일'), ('thu', '목요일'), ('fri', '금요일'), ('sat', '토요일'), ('sun', '일요일')], max_length=3, verbose_name='요일')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(verbose_name='종료 시간')),
                ('classroom', models.CharField(blank=True, max_length=100, verbose_name='강의실')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='academic.courseoffering', verbose_name='개설 강좌')),
            ],
            options={
                'verbose_name': '수업 시간',
                'verbose_name_plural': '수업 시간',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='offering_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academic.major', verbose_name='개설 전공'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20, unique=True, verbose_name='학번')),
                ('display_name', models.CharField(max_length=50, verbose_name='표시 이름')),
                ('admission_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='입학 연도')),
                ('current_semester', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='현재 학기')),
                ('status', models.CharField(choices=[('enrolled', '재학'), ('leave', '휴학'), ('graduated', '졸업')], default='enrolled', max_length=20, verbose_name='학적 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('primary_major', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_students', to='academic.major', verbose_name='주전공')),
                ('secondary_major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_students', to='academic.major', verbose_name='복수·부전공')),
            ],
            options={
                'verbose_name': '학생',
                'verbose_name_plural': '학생',
                'ordering': ['student_number'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enrolled', '수강 중'), ('dropped', '수강 취소'), ('completed', '이수 완료')], default='enrolled', max_length=20, verbose_name='수강 상태')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='수강 신청일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academic.courseoffering', verbose_name='개설 강좌')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academic.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '수강 신청',
                'verbose_name_plural': '수강 신청',
                'ordering': ['-offering__term__year', 'student__student_number', 'offering__course__code'],
            },
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code_snapshot', models.CharField(max_length=30, verbose_name='당시 과목 코드')),
                ('course_name_snapshot', models.CharField(max_length=150, verbose_name='당시 과목명')),
                ('credits_attempted', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='신청 학점')),
                ('credits_earned', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='취득 학점')),
                ('grade', models.CharField(choices=[('A+', 'A+'), ('A0', 'A0'), ('B+', 'B+'), ('B0', 'B0'), ('C+', 'C+'), ('C0', 'C0'), ('D+', 'D+'), ('D0', 'D0'), ('F', 'F'), ('P', 'Pass'), ('NP', 'Non-Pass'), ('W', '수강 철회'), ('I', '미완료')], max_length=2, verbose_name='성적')),
                ('grade_points', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4.5)], verbose_name='평점')),
                ('is_passed', models.BooleanField(verbose_name='이수 통과')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='수강 차수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_records', to='academic.academicterm', verbose_name='수강 학기')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_records', to='academic.course', verbose_name='과목')),
                ('offering', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_records', to='academic.courseoffering', verbose_name='개설 강좌')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='academic.student', verbose_name='학생')),
            ],
            options={
                'verbose_name': '성적·이수 기록',
                'verbose_name_plural': '성적·이수 기록',
                'ordering': ['-term__year', 'student__student_number', 'course__code', 'attempt_number'],
            },
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['term', 'status'], name='offering_term_status_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['course', 'term'], name='offering_course_term_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(fields=('course', 'term', 'section_number'), name='unique_course_term_section'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.CheckConstraint(condition=models.Q(('credits__gte', 0.5), ('credits__lte', 10)), name='course_offering_credits_range'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('capacity__gte', 1), _connector='OR'), name='course_offering_capacity_positive'),
        ),
        migrations.AddIndex(
            model_name='coursemeeting',
            index=models.Index(fields=['offering', 'day_of_week'], name='meeting_offering_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursemeeting',
            constraint=models.UniqueConstraint(fields=('offering', 'day_of_week', 'start_time'), name='unique_offering_meeting_time'),
        ),
        migrations.AddConstraint(
            model_name='coursemeeting',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='course_meeting_valid_time_range'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('default_credits__gte', 0.5), ('default_credits__lte', 10)), name='course_default_credits_range'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('admission_year__gte', 2000), ('admission_year__lte', 2100)), name='student_admission_year_range'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('current_semester__gte', 1), ('current_semester__lte', 20)), name='student_current_semester_range'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('secondary_major__isnull', True), models.Q(('primary_major', models.F('secondary_major')), _negated=True), _connector='OR'), name='student_different_secondary_major'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'status'], name='enrollment_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['offering', 'status'], name='enrollment_offering_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'offering'), name='unique_student_course_offering'),
        ),
        migrations.AddIndex(
            model_name='academicrecord',
            index=models.Index(fields=['student', 'term'], name='record_student_term_idx'),
        ),
        migrations.AddIndex(
            model_name='academicrecord',
            index=models.Index(fields=['student', 'course'], name='record_student_course_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicrecord',
            constraint=models.UniqueConstraint(fields=('student', 'course', 'term', 'attempt_number'), name='unique_student_course_term_attempt'),
        ),
        migrations.AddConstraint(
            model_name='academicrecord',
            constraint=models.CheckConstraint(condition=models.Q(('credits_attempted__gte', 0), ('credits_attempted__lte', 10)), name='academic_record_attempted_credits_range'),
        ),
        migrations.AddConstraint(
            model_name='academicrecord',
            constraint=models.CheckConstraint(condition=models.Q(('credits_earned__gte', 0), ('credits_earned__lte', 10)), name='academic_record_earned_credits_range'),
        ),
        migrations.AddConstraint(
            model_name='academicrecord',
            constraint=models.CheckConstraint(condition=models.Q(('credits_earned__lte', models.F('credits_attempted'))), name='academic_record_earned_lte_attempted'),
        ),
        migrations.AddConstraint(
            model_name='academicrecord',
            constraint=models.CheckConstraint(condition=models.Q(('grade_points__isnull', True), models.Q(('grade_points__gte', 0), ('grade_points__lte', 4.5)), _connector='OR'), name='academic_record_grade_points_range'),
        ),
        migrations.AddConstraint(
            model_name='academicrecord',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_number__gte', 1)), name='academic_record_attempt_positive'),
        ),
    ]
