# Generated by Django 5.2.17 on 2026-09-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='is_replaced_by_retaking',
            field=models.BooleanField(default=False, verbose_name='재수강으로 대체됨'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('major', '전공'), ('bsm', 'BSM'), ('general', '교양')], default='major', max_length=20, verbose_name='이수 구분'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_english',
            field=models.BooleanField(default=False, verbose_name='영어 강의'),
        ),
    ]
