# Generated by Django 5.2.17 on 2026-09-03 06:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_academicrecord_is_replaced_by_retaking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='curriculum_year',
            field=models.PositiveSmallIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='교육과정 적용연도'),
        ),
        migrations.AddField(
            model_name='student',
            name='program_track',
            field=models.CharField(choices=[('general', '일반과정'), ('advanced', '심화과정')], default='general', max_length=20, verbose_name='교육과정'),
        ),
        migrations.AddField(
            model_name='student',
            name='reference_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reference_students', to='academic.academicterm', verbose_name='시나리오 기준 학기'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('curriculum_year__gte', 2000), ('curriculum_year__lte', 2100)), name='student_curriculum_year_range'),
        ),
    ]
